In [ ]:
import numpy as np
import sklearn as sklearn
from sklearn.metrics import mean_squared_error
from numpy import array
import sklearn as sklearn
import scipy as scipy
from scipy.sparse import csr_matrix
from scipy import sparse
from sklearn. model_selection import train_test_split
import random
from copy import copy, deepcopy
from sklearn.metrics import mean_squared_error
from numpy import array
import pandas as pd
import time
from functools import lru_cache
from time import time
from time import process_time
from scipy import optimize
import sys
import math
import csv

from scipy import sparse
%matplotlib inline

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!unzip "/content/drive/MyDrive/u.data.zip"

Archive:  /content/drive/MyDrive/u.data.zip
  inflating: u.data                  


In [ ]:
# innstall java
!apt-get install openjdk-8-jdk-headless -qq > /dev/null

# install spark (change the version number if needed)
!wget -q https://archive.apache.org/dist/spark/spark-3.0.0/spark-3.0.0-bin-hadoop3.2.tgz

# unzip the spark file to the current folder
!tar xf spark-3.0.0-bin-hadoop3.2.tgz

# set your spark folder to your system path environment. 
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.0.0-bin-hadoop3.2"


# install findspark using pip
!pip install -q findspark

In [ ]:
!pip install pyspark

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 281.3 MB 44 kB/s 
     |████████████████████████████████| 199 kB 71.7 MB/s 
  Created wheel for pyspark: filename=pyspark-3.3.0-py2.py3-none-any.whl size=281764026 sha256=ec5a824d2fc4d6f3a7eeb01bbebddcf818a809c3f08e10132dc2326c17a746b1
  Stored in directory: /root/.cache/pip/wheels/7a/8e/1b/f73a52650d2e5f337708d9f6a1750d451a7349a867f928b885
Successfully built pyspark


In [ ]:
import pyspark as pyspark
from pyspark import SparkContext

ModuleNotFoundError: ignored

In [ ]:
import findspark
findspark.init()

In [ ]:
class q_learning:

  def __init__(self):
    
    self.epsilon = 0.2
    self.rho= 0
    self.eta= 0
    self.gamma = 0
    self.theta = 0
    self.omega = 0
    self.phi = 0
    # self.eta = 0
    self.qlearning_rate =  0.01
    self.needed_ids = []
    self.Q_table = []
    self.er = 100

    self.h_par = { 'rho': np.arange( 0 , 1 , 0.001 ), 'eta':  np.arange( 0 , 1 , 0.001 )
    # ,
    #       'gamma':  np.arange( 0 , 1 , 0.001), 'theta':  np.arange( 0 , 1 , 0.001 ),
    #       'omega':  np.arange( 0 , 1 , 0.001 ), 'phi':  np.arange( 0 , 1 , 0.001 ),
    #       'eta':  np.arange( 0 , 1 , 0.001 )
          }

     #adding to qtable rows to match the count of hyperparameters
    
    self.Q_table.append(np.zeros(len(self.h_par['rho'])))
    self.Q_table.append(np.zeros(len(self.h_par['eta'])))
      #self.Q_table.append( np.full(shape=len(self.h_par['rho']),fill_value=3))



  #take_action for i-th parameter
  def take_action(self, i):
    a = np.random.random()
    if a < self.epsilon:
      # print(' random action ')
      #finding the key corresponding to hyperparameter
      keys_list = list(self.h_par)
      key = keys_list[i]

      index = np.random.randint(1000)

      #saving the chosen index and value for further use
      self.needed_ids.append(index)
      value = self.h_par[key][index]

          # take greedy action
    else:
      # print(' greedy action ')
       #finding the row corresponding to parameter i and selecting the index resulting in highest q value
      q_row = self.Q_table[i]
      index = np.argmax(q_row)

      keys_list = list(self.h_par)
      key = keys_list[i]
      value = self.h_par[key][index]

      self.needed_ids.append(index)

    return index, value


  def update_Q(self, error):

        #take action for each hyperparameter
        # for j in range(7):
        #     take_action(j)

        # reward = (-1) * loss(h_par['alpha'][needed_ids[0]], h_par['beta'][needed_ids[1]],
        #                     h_par['gamma'][needed_ids[2]], h_par['theta'][needed_ids[3]],
        #                     h_par['omega'][needed_ids[4]], h_par['phi'][needed_ids[5]],
        #                     h_par['eta'][needed_ids[6]], x1, x2)


    reward =-error
    for idx, p in zip(self.needed_ids,range(2)):
      TD = reward - self.Q_table[p][idx]
      self.Q_table[p][idx] = self.Q_table[p][idx] + self.qlearning_rate * TD

  def select(self):
    final_list = []
    #selecting the best values for hyperparameters using Qtable
    for j in range(2):
        q_row = self.Q_table[j]
        index = np.argmax(q_row)
        keys_list = list(self.h_par)
        key = keys_list[j]
        print("parameter: ",j )
        print("value: ",self.h_par[key][index] )
        final_list.append(self.h_par[key][index])
    # print(final_list)
    return final_list
    




In [ ]:
# @lru_cache(maxsize=None)
def objective(P, Q, R, mask, rho):
    """
    The objective function of the complete problem 
    Input :
    P : Matrix of size C x I
    Q : Matrix of size U x C
    R : Matrix of size U x I
    mask : Matrix 0-1 of size U x I
    rho : positif real 
    Output :
    val : value of the function 
    grad_P : gradient P
    grad_Q : gradient  Q
    """
    predic = Q.dot(P)
    r = (R - predic ) * mask
    # print("rmse", np.sqrt(mean_squared_error(R,  predic)))
    er = np.sum(r)
    obj.update_Q(er)
    # obj.er = er
    

    val = np.sum(r ** 2)/2. + rho /2. * (np.sum(Q ** 2) + np.sum(P ** 2))

    grad_P =+np.dot(Q.T,r) -rho * Q
    # print(grad_P)
    # norm = np.linalg.norm(grad_P)
    # if norm>0.01:
    #   grad_P= 0.01* grad_P/norm
    # elif norm<-0.01:
    #   grad_P = -0.01* grad_P/norm

    grad_Q =+np.dot(r, P.T) - rho * P
    # norm_2 = np.linalg.norm(grad_Q)
    # if norm_2>0.01:
    #   grad_Q = 0.01 * grad_Q/norm_2
    # elif norm_2<-0.01:
    #   grad_Q =-0.01*grad_Q/norm_2

    return val, grad_P, grad_Q


def objective_Q(P0, Q, R, mask, rho):
    """
    This function returns two values : 
        -The value of the objective function at P0 fixed 
        -The value of the gradient of Q 
    """
    val,_ ,grad_Q = objective(P0, Q, R, mask, rho)

    return (val, grad_Q)


def objective_P(P, Q0, R, mask, rho):
    """
    This function returns two values : 
        -The value of the objective function at Q0 fixed 
        -The value of the gradient of P
    """
    val, grad_P,_ = objective(P, Q0, R, mask, rho)

    return (val, grad_P)


def outputMatrix(A, path):
    """
    This function outputs a matrix to a csv file
    """
    f = open(path, 'w', 100)
    rows= A.shape[0]
    cols = A.shape[1]
    for row in range(rows):
        for col in range(cols):  
            if col == cols-1:
                f.write(str(A[row,col])) 
            else:
                f.write(str(A[row,col]) + ",")
        f.write("\n")

    f.flush()
    f.close()
def load_data(filename="u.data" , small_data=True):
    """
    This function returns :
        R : the matrix user-item containing the ratings
        mask : matrix is equal to 1 if a score existes and 0 otherwise
    """
    data = np.loadtxt(filename, dtype=int)
    
    R = sparse.csr_matrix((data[:, 2], (data[:, 0]-1, data[:, 1]-1)),dtype=float)
    mask = sparse.csr_matrix((np.ones(data[:, 2].shape),(data[:, 0]-1, data[:, 1]-1)), dtype=bool )

    # take a small part of the whole data for testing 
    if small_data is True:
        R = (R[0:100, 0:100].copy())
        mask = (mask[0:100, 0:100].copy())
        
        
    return R.toarray(), mask.toarray()



In [ ]:
# rho = 0.2
C = 6 # Number of factors
nbr_iter = 50 # number of iterations
block_number = 5 # number of blocks to take from the matrix

In [ ]:
def SGD(R, Q, P, mask, obj):
    """
    This function is an implementation of the SGD algorithm described above.
    Input : R, Q, P, mask
    Output : Q, P, n
    """
    
    # global rho
    # rho=0.01
    # first step size
    R_new = R.nonzero()
    n = R_new[0].size
    # for iter in range(5):
 

    for i in range(n):
      if i==0:
        rho = 0.1
        eta = 0.1
      else:
        obj.needed_ids = []
      #needed ids will be filled
        obj.take_action(0)
        obj.take_action(1)
        rho = obj.h_par['rho'][obj.needed_ids[0]]
        eta = obj.h_par['eta'][obj.needed_ids[1]]

      
      
      print("rho",rho)
      print("eta",eta)
      print("n",n)
      print("i",i)
        
      j = random.randint(0, n-1) # Pick randomly an element j
      row, col = R_new[0][j], R_new[1][j] # retrieve the row and column of the random j
        
      # take a small blocks from R, mask, Q and P
      Ri = R[row,col] 
      maski = mask[row,col]
      Qi = Q[row,:]
      Pi = P[:,col]
        
      # compute the gradient of Qi and Pi
      _, grad_Q = objective_Q(Pi, Qi, Ri, maski, rho)
      _, grad_P = objective_P(Pi, Qi, Ri, maski, rho)
      # eta = eta * (1 + i) ** (- 0.5)
        
      # update the blocks of P and Q
      Q[row,:] = Qi  - eta * grad_Q
      P[:,col] = Pi - eta * grad_P
      # print(np.linalg.norm(Q[row,:]))
      norm = np.linalg.norm(Q[row,:])
      if norm>0.01:
        Q[row,:]= 0.01* Q[row,:]/norm
      elif norm<-0.01:
        Q[row,:] = -0.01* Q[row,:]/norm
      
      norm_2 = np.linalg.norm(P[:,col])
      if norm>0.01:
        P[:,col]= 0.01* P[:,col]/norm_2
      elif norm<-0.01:
        P[:,col] = -0.01* P[:,col]/norm_2

      



    
        
    return Q, P

In [ ]:
global R, P, Q
# spark = SparkContext.getOrCreate()
# output_Q = "Q.csv"
# output_P = "P.csv"

#load data
R, mask = load_data(filename="u.data" , small_data=False)
print(R, mask)
U = len(R)
I = len(R[0])

Q = np.random.random_sample((R.shape[0], 10))
P = np.random.random_sample((10, R.shape[1]))
t = time()
obj = q_learning()
print("Start Process ....")
Q, P = SGD(R, Q, P, mask, obj)
print("Process finished in %s s"%(time()-t))
fi_list = obj.select()
rho = fi_list[0]
eta = fi_list[1]


# print(Q)
# print(Q.dot(P))
print(R)

RMSE =np.sqrt(mean_squared_error(R,  Q.dot(P)))
print("RMSE",RMSE)
# Wrtie the obtained Matrices to csv file
# outputMatrix(P,output_P)
# outputMatrix(Q,output_Q)

Streaming output truncated to the last 5000 lines.
i 99381
[-0.00741225 -0.00944947 -0.02221609  0.00188358 -0.00660012 -0.01509499
 -0.02160783 -0.01898302 -0.02581116 -0.00164878]
[-0.00741225 -0.00944947 -0.02221609  0.00188358 -0.00660012 -0.01509499
 -0.02160783 -0.01898302 -0.02581116 -0.00164878]
rho 0.198
eta 0.97
n 100000
i 99382
[-0.00735472 -0.00889949 -0.02177575  0.00199779 -0.00631699 -0.01474667
 -0.02118444 -0.0182793  -0.02552969 -0.00158186]
[-0.00735472 -0.00889949 -0.02177575  0.00199779 -0.00631699 -0.01474667
 -0.02118444 -0.0182793  -0.02552969 -0.00158186]
rho 0.5760000000000001
eta 0.5680000000000001
n 100000
i 99383
[-0.00527896 -0.0064721  -0.01539425  0.00126053 -0.00464239 -0.01046817
 -0.0151301  -0.01307175 -0.01821251 -0.00122412]
[-0.00527896 -0.0064721  -0.01539425  0.00126053 -0.00464239 -0.01046817
 -0.0151301  -0.01307175 -0.01821251 -0.00122412]
rho 0.516
eta 0.553
n 100000
i 99384
[-0.00539023 -0.0065396  -0.01583641  0.00126177 -0.00457466 -0.010

In [ ]:
print(obj.Q_table)

In [ ]:
relative_error = np.linalg.norm(mask*(R - np.dot(Q, P))) / np.linalg.norm(R) * 100
print("Relative error : %f"%relative_error)

Relative error : 100.000043


In [ ]:
R_result = Q.dot(P)
print(Q.dot(P))
print(R)
print(P.shape)
print(Q.shape)

[[-9.99987272e-07 -9.99991827e-07 -9.99996633e-07 ... -5.72521241e-07
  -6.71604116e-07 -1.77445700e-03]
 [-9.99999126e-07 -9.99997630e-07 -9.99981228e-07 ... -5.68752716e-07
  -6.69220597e-07 -1.76731749e-03]
 [-9.99988862e-07 -9.99992509e-07 -9.99996581e-07 ... -5.71957896e-07
  -6.71629135e-07 -1.77438769e-03]
 ...
 [-9.99992164e-07 -9.99988766e-07 -9.99959623e-07 ... -5.66798304e-07
  -6.68280249e-07 -1.76379713e-03]
 [-9.99806087e-07 -9.99831566e-07 -9.99883978e-07 ... -5.78018463e-07
  -6.80849275e-07 -1.79264553e-03]
 [-9.99983875e-07 -9.99988496e-07 -9.99994367e-07 ... -5.72489903e-07
  -6.72126795e-07 -1.77529796e-03]]
[[5. 3. 4. ... 0. 0. 0.]
 [4. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [5. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 5. 0. ... 0. 0. 0.]]
(10, 1682)
(943, 10)
